# 3.wite the program to add .subtrct ,multipy and divide usin the data from the user
a=float(input("Enter the value of a:"))
b=float(input("Enter the value of b:"))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
